### ISSUE TITLE
protocol failed

### ISSUE THREAD

**Issue by oscarsaizg** [scipion-chem/scipion-chem-schrodinger#22]
00001:   Traceback (most recent call last):
00002:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 205, in run
00003:       self._run()
00004:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 256, in _run
00005:       resultFiles = self._runFunc()
00006:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _runFunc
00007:       return self._func(*self._args)
00008:     File "/home/osaiz/scipion3/scipion-chem-schrodinger/pwchemSchrodinger/protocols/protocol_sitemap.py", line 77, in convertStep
00009:       self.runJob(prog, args, cwd=self._getExtraPath())
00010:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1535, in runJob
00011:       kwargs['env'] = self._getEnviron()
00012:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1523, in _getEnviron
00013:       return self.getClassPackage().Plugin.getEnviron()
00014:     File "/home/osaiz/scipion3/scipion-chem-schrodinger/pwchemSchrodinger/__init__.py", line 62, in getEnviron
00015:       environ.update({
00016:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/utils.py", line 653, in update
00017:       self.set(k, v, position)
00018:     File "/home/osaiz/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/utils.py", line 644, in set
00019:       self[varName] = varValue + os.pathsep + self[varName]
00020:   TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
00021:   Protocol failed: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by oscarsaizg** [comment]
![Captura de pantalla 2024-09-03 115450](https://github.com/user-attachments/assets/97230e0c-1f35-456a-9ec1-78808a04d554)
